### ISSUE TITLE
Some think about API Gateway

### ISSUE THREAD

**Issue by alexsandro-xpt** [vietnam-devs/coolstore-microservices#27]
Ocelot is good tool for that https://github.com/ThreeMammals/Ocelot

**Comment by thangchung** [comment]
Yeah. We're using Ocelot in the company for some of projects, but in this demo project, we would like to use [Nginx](https://github.com/vietnam-devs/coolstore-microservices/blob/master/deploys/charts/coolstore/templates/nginx-ingress.yaml) or [Istio Gateway](https://github.com/vietnam-devs/coolstore-microservices/blob/master/deploys/charts/coolstore-istio/templates/gateway.yaml) for the demo for service mesh.

**Comment by alexsandro-xpt** [comment]
Alright  @thangchung, I'm using AKS with LoadBalance for each service endpoint, could I user Istio at my aproach without Istio Gateway? I feel an Ingress is a point of failure in the cluster and I would like to use Loadbalance.

**Comment by thangchung** [comment]
In that case, I think you should investigate to config a LoadBalancer in front of the gateway. To be honest, I didn't use it so far.

**Comment by alexsandro-xpt** [comment]
Istio Ingress already a LoadBalance but I don't want put all services under an Ingress. I don't know how to configure that with Istio, I'm looking for...
