### ISSUE TITLE
CQRS and Event Source

### ISSUE THREAD

**Issue by alexsandro-xpt** [vietnam-devs/coolstore-microservices#28]
What did know about an demo implemention with RabbitMQ between some microsservices under CQRS and Event Source?

**Comment by thangchung** [comment]
@alexsandro-xpt We will have that in next couple of days. Not RabbitMQ, but we gonna use Kafka/Redis for the event bus. The architecture is not CQRS/Event Sourcing yet, it just the event-driven architecture. In meantime, if you want to see how it works, you can access to the demo at https://github.com/cloudnative-netcore/netcorekit/blob/master/samples/TodoApi/Startup.cs
