### ISSUE TITLE
[Rust] Implement one service using Rust 

### ISSUE THREAD

**Issue by thangchung** [vietnam-devs/coolstore-microservices#32]
Especially in [rocket framework](https://github.com/SergioBenitez/Rocket) and [yew](https://github.com/DenisKolodin/yew)

**Comment by thangchung** [comment]
We might consider using https://github.com/actix/actix-web

**Comment by thangchung** [comment]
https://github.com/carllerche/tower-web

**Comment by toanvo288** [comment]
Hi @thangchung why do we consider Rust? How's about other languages?

**Comment by trumhemcut** [comment]
because of this? active-web is the fastest one in the market which a Rust-based web framework ![image](https://user-images.githubusercontent.com/5198341/63911113-652c2900-ca53-11e9-81a3-8e7ee5a40107.png)

**Comment by thangchung** [comment]
All things are planing anh @toanvo288, anh @trumhemcut. I have a look around all languages which might be the best for demo. Look at this https://functional.works-hub.com/learn/functional-programming-jargon-in-rust-1b555, one programming language to rule them all. I doesn't have a decision yet =))

**Comment by toanvo288** [comment]
Thanks @thangchung, I still keep an eye on your decision. :)
