### ISSUE TITLE
Long running (workflow and Sagas) 

### ISSUE THREAD

**Issue by thangchung** [vietnam-devs/coolstore-microservices#4]
Articles:
- [Workflow & Saga](https://github.com/flowing/flowing-retail/blob/master/README.md)
- [Use Camunda without touching Java and get an easy-to-use REST-based orchestration and workflow engine](https://blog.bernd-ruecker.com/use-camunda-without-touching-java-and-get-an-easy-to-use-rest-based-orchestration-and-workflow-7bdf25ac198e)
- https://speakerdeck.com/bobbycalderwood/commander-decoupled-immutable-rest-apis-with-kafka-streams

Camuda Client:
- https://github.com/jlucansky/Camunda.Api.Client
- https://github.com/berndruecker/camunda-dot-net-showcase
- https://github.com/berndruecker/camunda-dot-net-showcase/blob/master/CamundaClient <= upgrade .NET 2.0 and PR (if need)

Source code:
- https://github.com/flowing/flowing-retail

Presentation:
- https://skillsmatter.com/skillscasts/9853-long-running-processes-in-ddd

.NET Workflow libs:
- https://github.com/elsa-workflows/elsa-core

NATS
- https://nats.io/blog/use-cases-for-persistent-logs-with-nats-streaming/
- https://nats.io/blog/ariane-mapping-microservice-with-nats/

**Comment by thangchung** [comment]
This is what I think we can work now https://github.com/zeebe-io/zeebe-client-csharp

**Comment by thangchung** [comment]
With distributed workflow in demo, we might only need OutBox/Inbox pattern

**Comment by toanvo288** [comment]
Hi em, @thangchung, this is first time I hear from you about Inbox pattern. I only know about Transactional Outbox pattern. Could you possibly introduce something about Inbox pattern?

**Comment by thangchung** [comment]
Hi anh @toanvo288, something I found out just like the image below

![image](https://user-images.githubusercontent.com/422341/64474409-cca64f00-d19e-11e9-9239-74974c07130f.png)

I will implement and test it soon

**Comment by toanvo288** [comment]
Many thanks @thangchung. It is really useful to understand.

**Comment by karoldeland** [comment]
Have you consider implementing it with NServiceBus?
https://docs.particular.net/samples/hosting/docker/
https://docs.particular.net/nservicebus/sagas/

**Comment by thangchung** [comment]
@karoldeland Thank you for the information. But we are not going to use NServiceBus with RabbitMQ, instead of using [NATS](https://github.com/nats-io) protocol in [CNCF](https://landscape.cncf.io/category=streaming-messaging&format=card-mode&grouping=category) ecosystem for developing the cloud-native apps
