### ISSUE TITLE
Compilation issue

### ISSUE THREAD

**Issue by userid2018** [vietnam-devs/coolstore-microservices#46]
I am trying to compile code from master branch. I took latest version of netcorekit and getting compiling issues. please help.

**Comment by userid2018** [comment]
any pointers?

**Comment by thangchung** [comment]
Run `git submodule foreach git pull origin master` command at the root of the project, then you will be able to compile it

**Comment by userid2018** [comment]
could you please confirm which branch of netcorekit will work with dev branch of this project

**Comment by thangchung** [comment]
Can you cant run `docker-compose build` on your laptop?

**Comment by userid2018** [comment]
docker-compose build works but i want to compile entire thing in Visual studio.

just want to know which version of netcorekit is compatible with this project.

**Comment by userid2018** [comment]
> docker-compose build works but i want to compile entire thing in Visual studio.
> 
> just want to know which version of netcorekit is compatible with this project.

any pointers

**Comment by thangchung** [comment]
@userid2018 Please try to get `netcorekit` at hash `bfcd53395fd3bc280b7030b6ae60a1bb83f5db7a` and https://github.com/cloudnative-netcore/netcorekit/commit/bfcd53395fd3bc280b7030b6ae60a1bb83f5db7a
