### ISSUE TITLE
Problem with running project in Docker.

### ISSUE THREAD

**Issue by kevinvdm88** [vietnam-devs/coolstore-microservices#50]
Hi 

Thanks for the clear repository and architecture  :) !

I try to run this project in Docker with the command "docker-compose up" but I directly get this error: 
docker-compose : Service 'migration-data' depends on service 'sqlserver' which is undefined.

Can someone help me what i'm doing wrong ?
With other projects I don't have any problems with docker.

Thanks.

**Comment by thangchung** [comment]
We are struggling to work on the new version based on Dapr and Tye. Keep waiting a little bit.
