### ISSUE TITLE
Question: communication between services?

### ISSUE THREAD

**Issue by vanthoainguyen** [vietnam-devs/coolstore-microservices#51]
Hi, 

When a product is added to ShoppingCart service, how would that event update the Stock availability in Inventory service? Is it via event stream or via api update? 

There are a few interesting use cases i'm facing:
- User add a near out of stock item to shopping cart, system update the inventory. However, the customer won't submit the order soon, how would you let other customer buy that same product?
- If Inventory service is degraded or down, would it affect checkout journey? 

Thanks.

**Comment by thangchung** [comment]
Hi anh @vanthoainguyen, I think right now the good option is using Debezium to do the CDC on the source and the destination database sources. It is hard to maintain the sync data between Cart and Stock. I have referenced some documents at https://debezium.io/blog/2019/02/19/reliable-microservices-data-exchange-with-the-outbox-pattern/
