### ISSUE TITLE
Changes in README and .env

### ISSUE THREAD

**Issue by yasir2000** [vietnam-devs/coolstore-microservices#54]
Installation via docker should be replaced with :
docker-compose -f docker-compose.base.yml -f docker-compose.base.override.yml -f docker-compose.yml -f docker-compose.override.yml up -d
And .env to catch user home instead of : 
LOCAL_NUGET_PATH=/c/Users/Thang Chung/.nuget/packages

**Comment by thangchung** [comment]
We are working on the new version with `tye` and `dapr`. Whenever we did it, we will remove everything related to the hard code you mentioned.
