### ISSUE TITLE
Question: Any plans for multitenancy?

### ISSUE THREAD

**Issue by mikecasas** [vietnam-devs/coolstore-microservices#56]
Thanks so much for the project and guidance. Any plans for a multitenant design?

**Comment by thangchung** [comment]
@mikecasas We don't have a plan for multi-tenancy apps and architectures right now. I think `abp` libs and frameworks at https://github.com/abpframework/abp/tree/dev/modules/tenant-management have the right approach and everything that needs to build the multi-tenancy apps

I close this issue now. Feel free to re-open if you want to discuss more. Thank you!
