### ISSUE TITLE
'run' failed

### ISSUE THREAD

**Issue by theth99** [vietnam-devs/coolstore-microservices#58]
Hi team,

I run with command but get error:

$ tye run
Loading Application Details...
Drats! 'run' failed:
        Evaluated project metadata file could not be found for service webapigatewayapp

**Comment by cuno92** [comment]
**Updated new error message when execute "$ tye run".**
`An unhandled exception has occurred, how unseemly:
System.ArgumentException: An item with the same key has already been added. Key: placement
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at Microsoft.Tye.ApplicationBuilderExtensions.ToHostingApplication(ApplicationBuilder application) in /_/src/tye/ApplicationBuilderExtensions.cs:line 183
   at Microsoft.Tye.Program.<>c.<<CreateRunCommand>b__18_0>d.MoveNext() in /_/src/tye/Program.RunCommand.cs:line 125
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Invocation.CommandHandler.GetResultCodeAsync(Object value, InvocationContext context)
   at System.CommandLine.Invocation.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseParseErrorReporting>b__19_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass17_0.<<UseMiddleware>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass14_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseVersionOption>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseDebugDirective>b__10_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass12_0.<<UseExceptionHandler>b__0>d.MoveNext()`

**Comment by thangchung** [comment]
Hi. Please make sure that you stop some containers like `placement`, `redis`, and `zipkin` in your local development environment. The error might show that there is a container (placement) that has already run

**Comment by arthurbai** [comment]
> Hi. Please make sure that you stop some containers like `placement`, `redis`, and `zipkin` in your local development environment. The error might show that there is a container (placement) that has already run

all local container were removed already.
this issue was still happed when run 'tye run'

the tye version is 0.7.0-*

**Comment by thangchung** [comment]
We're going to upgrade to `dapr 1.1`, we have found the issue you submitted and fixed in https://github.com/vietnam-devs/coolstore-microservices/tree/feature/devday-jun2021. Plz get the source from that branch and build it during we are working on the new version of coolstore-microservices.

/cc @tungphuong

**Comment by arthurbai** [comment]
thanks , it works well.

and i try to open
 http://localhost:5000/, then found preview is very different with  introdution, such as no swagger, no ui
do you know  how to get them ?

**Comment by arthurbai** [comment]
![image](https://user-images.githubusercontent.com/20101253/119757841-8f528b00-be73-11eb-9f1c-e95fbc2b6555.png)
![image](https://user-images.githubusercontent.com/20101253/119757857-94afd580-be73-11eb-9aae-a88a994f285e.png)

**Comment by thangchung** [comment]
@arthurbai We haven't updated the README file according to the changes in the new branch. We will work on that soon. Thank you for your feedbacks

**Comment by huynhtangiau** [comment]
> **Updated new error message when execute "$ tye run".**
> 
> `An unhandled exception has occurred, how unseemly: System.ArgumentException: An item with the same key has already been added. Key: placement at System.Collections.Generic.Dictionary 2.TryInsert(TKey key, TValue value, InsertionBehavior behavior) at Microsoft.Tye.ApplicationBuilderExtensions.ToHostingApplication(ApplicationBuilder application) in /_/src/tye/ApplicationBuilderExtensions.cs:line 183 at Microsoft.Tye.Program.<>c.<<CreateRunCommand>b__18_0>d.MoveNext() in /_/src/tye/Program.RunCommand.cs:line 125 --- End of stack trace from previous location where exception was thrown --- at System.CommandLine.Invocation.CommandHandler.GetResultCodeAsync(Object value, InvocationContext context) at System.CommandLine.Invocation.ModelBindingCommandHandler.InvokeAsync(InvocationContext context) at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseParseErrorReporting>b__19_0>d.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass17_0.<<UseMiddleware>b__0>d.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass14_0.<<UseHelp>b__0>d.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseVersionOption>b__0>d.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseDebugDirective>b__10_0>d.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass12_0.<<UseExceptionHandler>b__0>d.MoveNext()`

i got same issue, pls help me resolve it
