### ISSUE TITLE
Yarp Integration with Dapr

### ISSUE THREAD

**Issue by goldytech** [vietnam-devs/coolstore-microservices#72]
I want to integrate YARP with DAPR. My use case is that when a user hits the yarp URL, the downstream of it must invoke the DAPR sidecar URL for service invocation Eg.

```
http(s)://<Yarp service >/api/< service name >/XXXXX (Upstream)
 To 
http://<Dapr-sidecar>/v1.0/invoke/< service name >/method/XXXXX (Downstream)
```
I'm not sure how I configure this as YARP routes.

Please help.

**Comment by thangchung** [comment]
You can follow this issue in the YARP repo => https://github.com/microsoft/reverse-proxy/issues/967
Feel free to open up if you have more concerns. Thank you
